TASK: "csnet-L-x1"

GPU: 0

MODEL:
  ARCH: "csnet"
  BASIC_SPLIT: [0.5,0.5]

DATA:
  DIR: "/data/swook/dataset/duts/DUTS-TE"
  PRETRAIN: ''
  BATCH_SIZE: 24
  WORKERS: 8
  IMAGE_H: 224
  IMAGE_W: 224
  RESUME: ""

VAL:
  DIR: "/data/swook/dataset/duts/DUTS-TE"

TEST:
  DATASET_PATH: "/data/swook/dataset/duts/DUTS-TE"
  # DATASETS: ['ECSSD','DUT-OMRON','DUTS-TE','PASCAL-S','HKU-IS','SOD']
  DATASETS: ['DUTS-TE']
  INTERVAL: 5
  ENABLE: False
  IMAGE_H: 224
  IMAGE_W: 224
  TESTALL: False
  CHECKPOINT:  "CSNet/checkpoints/csnet-L-x1/csnet-L-x1.pth.tar"
  MODEL_CONFIG: "CSNet/checkpoints/csnet-L-x1/csnet-L-x1.bin"